---
- name: copy configs
  template:
    src:   templates/60-elk.conf.j2
    dest:  /etc/rsyslog.d/60-elk.conf
  register: rsyslog_client_config_status

- name: restart rsyslog
  systemd:
    name:    rsyslog
    state:   restarted
  when: rsyslog_client_config_status.changed