---
- name: install filebeat package
  apt:
    name: ['filebeat']
    state:  present

- name: make conf dir
  file:
    dest: /etc/filebeat/inputs.d
    state: directory

- name: copy configs
  template:
    src:   templates{{ item }}.j2
    dest:  "{{ item }}"
    backup: true
  with_items:
    - /etc/filebeat/filebeat.yml
    - /etc/filebeat/inputs.d/log_app.yml
  register: filebeat_config_status

- name: restart filebeat
  systemd:
    name:    filebeat
    state:   restarted
  when: filebeat_config_status.changed

- name: start and enable filebeat
  systemd:
    name:    filebeat
    state:   started
    enabled: yes